FROM quay.io/keycloak/keycloak:latest

ENV KEYCLOAK_ADMIN=admin
ENV KEYCLOAK_ADMIN_PASSWORD=1234

ENV KC_HOSTNAME=osamhack2022-v2-web-mili-meet-broker-gv5wqp76qjx2v66p-8080.preview.app.github.dev
ENV KC_HOSTNAME_ADMIN=osamhack2022-v2-web-mili-meet-broker-gv5wqp76qjx2v66p-8080.preview.app.github.dev
ENV KC_HOSTNAME_STRICT_HTTPS=true
ENV KC_HTTPS_PORT=443
ENV KC_PROXY=edge

CMD [ "start-dev" ]
